/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdStudyRouteImport } from './routes/api/ad-study'
import { Route as ApiAudioRouteImport } from './routes/api/audio'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiPackRouteImport } from './routes/api/pack'
import { Route as ApiResolveRouteImport } from './routes/api/resolve'
import { Route as ApiStudyRouteImport } from './routes/api/study'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdStudyRoute = ApiAdStudyRouteImport.update({
  id: '/api/ad-study',
  path: '/api/ad-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackRoute = ApiPackRouteImport.update({
  id: '/api/pack',
  path: '/api/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyRoute = ApiStudyRouteImport.update({
  id: '/api/study',
  path: '/api/study',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ad-study': typeof ApiAdStudyRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/file': typeof ApiFileRoute
  '/api/pack': typeof ApiPackRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/study': typeof ApiStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ad-study': typeof ApiAdStudyRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/file': typeof ApiFileRoute
  '/api/pack': typeof ApiPackRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/study': typeof ApiStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ad-study': typeof ApiAdStudyRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/file': typeof ApiFileRoute
  '/api/pack': typeof ApiPackRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/study': typeof ApiStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ad-study'
    | '/api/audio'
    | '/api/file'
    | '/api/pack'
    | '/api/resolve'
    | '/api/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/ad-study'
    | '/api/audio'
    | '/api/file'
    | '/api/pack'
    | '/api/resolve'
    | '/api/study'
  id:
    | '__root__'
    | '/'
    | '/api/ad-study'
    | '/api/audio'
    | '/api/file'
    | '/api/pack'
    | '/api/resolve'
    | '/api/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdStudyRoute: typeof ApiAdStudyRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiPackRoute: typeof ApiPackRoute
  ApiResolveRoute: typeof ApiResolveRoute
  ApiStudyRoute: typeof ApiStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad-study': {
      id: '/api/ad-study'
      path: '/api/ad-study'
      fullPath: '/api/ad-study'
      preLoaderRoute: typeof ApiAdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pack': {
      id: '/api/pack'
      path: '/api/pack'
      fullPath: '/api/pack'
      preLoaderRoute: typeof ApiPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study': {
      id: '/api/study'
      path: '/api/study'
      fullPath: '/api/study'
      preLoaderRoute: typeof ApiStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdStudyRoute: ApiAdStudyRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiFileRoute: ApiFileRoute,
  ApiPackRoute: ApiPackRoute,
  ApiResolveRoute: ApiResolveRoute,
  ApiStudyRoute: ApiStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
